apiVersion: batch/v1
kind: Job
metadata:
  name: hive-metastore-init
  namespace: dtd-datavisualization
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: schematool
          image:  registry.pusilkom.com/dtd/hivemetastore:latest    # pakai image hasil build Dockerfile.hivemetastore
          env:
            - name: METASTORE_DB_HOSTNAME
              valueFrom: { configMapKeyRef: { name: data-lake-config, key: POSTGRES_HOST } }
            - name: METASTORE_DB_NAME
              valueFrom: { configMapKeyRef: { name: data-lake-config, key: POSTGRES_DB } }
            - name: METASTORE_DB_PORT
              valueFrom: { configMapKeyRef: { name: data-lake-config, key: POSTGRES_PORT } }
            - name: METASTORE_DB_USER
              valueFrom: { secretKeyRef: { name: metastore-db, key: username } }
            - name: METASTORE_DB_PASSWORD
              valueFrom: { secretKeyRef: { name: metastore-db, key: password } }
          command: ["/bin/sh","-lc"]
          args:
            - |
              schematool -dbType postgres -validate || \
              schematool -dbType postgres -initSchema --verbose || true
      imagePullSecrets:
        - name:  registry-dtd