#single node install config
coordinator=true
node-scheduler.include-coordinator=true
http-server.http.port=8080
# discovery-server.enabled=true
discovery.uri=http://trino-cluster-trino:8080
http-server.authentication.type=PASSWORD
internal-communication.shared-secret=trino-internal-secret-2024

# Proxy support for Traefik HTTPS
http-server.process-forwarded=true
http-server.authentication.allow-insecure-over-http=true
web-ui.preview.enabled=true
web-ui.enabled=true
# HTTP Server Request Logging
http-server.log.enabled=true

# Example: worker JVM -Xmx = 4G
# query.max-memory-per-node=1GB        # per-node user memory cap (~25–40% heap)
# query.max-total-memory-per-node=2GB  # includes revocable memory
# memory.heap-headroom-per-node=1GB    # leave headroom for JVM/GC
# query.max-memory=10GB                # cluster-wide user memory cap
# query.max-total-memory=20GB          # cluster-wide total cap (> query.max-memory)

# spill-enabled=true
# spiller-spill-path=/data/trino-spill1
# optional caps/tuning:
# max-spill-per-node=300GB
# query-max-spill-per-node=250GB

